### ISSUE TITLE
Method is_strongly_connected is implemented incorrectly

### ISSUE THREAD

**Issue by icezyclon** [DES-Lab/AALpy#12]
**Problem:**
The method `is_strongly_connected` of the `Automaton` class is faulty, which will result in incorrectly determining automatons as strongly connected, even though they aren't.

**Explanation:**
The method uses `itertools.combinations` to check ~all~ possible transitions.
However, combinations *ignore ordering* meaning they treat transitions as bi-directional!
This is not the case for this automata where each state has its own transitions.

**Solution:**
Using `itertools.permutations` instead of `itertools.combinations` to fix the problem, because permutations differ in their ordering.

**Example:**
Assume we have the states *a*, *b* and *c* and assume that *a* is the starting state that has connections to *b* and *c*.
If there are no connections back to *a* from both *b* and *c* then the old algorithm would incorrectly say that it is strongly connected, even though it clearly isn't (a is unreachable).
`Combination` would say that the automaton is strongly connected, while `permutations` would check connections back to *a* determining that it isn't.

Starting state: *a*
Transitions: `a -> b`, `b -> c`, `c -> b`

```python
>>> from itertools import combinations, permutations
>>> states = ['a', 'b', 'c']
>>> list(combinations(states, 2))
[('a', 'b'), ('a', 'c'), ('b', 'c')]  # no check from any state to a
>>> list(permutations(states, 2))
[('a', 'b'), ('a', 'c'), ('b', 'a'), ('b', 'c'), ('c', 'a'), ('c', 'b')]  # checks back to a
```

**Comment by emuskardin** [comment]
Thanks for pointing that out, issue is resolved
