### ISSUE TITLE
Circular Inport on Oracle Import

### ISSUE THREAD

**Issue by icezyclon** [DES-Lab/AALpy#22]
**Problem:**
Importing any oracle from `aalpy.oracles` will result in a circular import on version **1.1.7** which is the newest version from pypi. This issue also exists on the most current commit: a59df07c3049dc15b97d3659739084181d89097e
Minimum working example:
```python
from aalpy.oracles import WMethodEqOracle
```
Resulting in:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from aalpy.oracles import UserInputEqOracle
  File "USER/.virtualenvs/avlstar4/lib/python3.8/site-packages/aalpy/oracles/__init__.py", line 9, in <module>
    from .UserInputEqOracle import UserInputEqOracle
  File "USER/.virtualenvs/avlstar4/lib/python3.8/site-packages/aalpy/oracles/UserInputEqOracle.py", line 2, in <module>
    from aalpy.utils import visualize_automaton
  File "USER/.virtualenvs/avlstar4/lib/python3.8/site-packages/aalpy/utils/__init__.py", line 4, in <module>
    from .ModelChecking import model_check_experiment, mdp_2_prism_format, model_check_properties, get_properties_file, get_correct_prop_values, compare_automata
  File "USER/.virtualenvs/avlstar4/lib/python3.8/site-packages/aalpy/utils/ModelChecking.py", line 9, in <module>
    from aalpy.oracles import RandomWMethodEqOracle
ImportError: cannot import name 'RandomWMethodEqOracle' from partially initialized module 'aalpy.oracles' (most likely due to a circular import) (USER/.virtualenvs/avlstar4/lib/python3.8/site-packages/aalpy/oracles/__init__.py)
```

**Explanation:**
Basically, the __init__.py of oracles loads the UserInputEqOracle, which in turn requires visualize_automata, in the process initializing __init__.py of utils which loads ModelChecking which requires the RandomWMethodEqOracle from the partially initialized __init__.py of oracles.

**Notes:**
1) Running tests automatically would probably prevent such easy errors from getting pushed to pypi. I would recommend a tool like `pre-commit`, if you would like, I could set up a basic configuration for AALpy.
2) Please tag the versions which are pushed to pypi also here. This would have allowed me to easily find the commit that resulted in this issue.
3) I switched to version **1.1* for now which does not have this problem.

**Comment by icezyclon** [comment]
Note: After a bisection search I found the first broken commit:

commit 49aa8c0a5260371acb9d433e55c961600ad6c48c
Date:   Tue Dec 14 19:52:16 2021 +0100
Message: fix bug in WMethod char. set computation, add comparison of det. automata

Hopefully, that helps

**Comment by emuskardin** [comment]
Thanks once again.
I will reach out to you about `pre-commit` in the near feature :)
