### ISSUE TITLE
Could the merging heuristics be abandoned in RPNI passive deterministic automata learning?

### ISSUE THREAD

**Issue by wqqqy** [DES-Lab/AALpy#33]
Hi, 
I started using RPNI algorithm in the package recently.
I wonder if the merging heuristics in RPNI passive deterministic automata learning could be abandoned or customized?

**Comment by emuskardin** [comment]
Hi,

currently no advanced heuristics are used. We intend to add them in the future, but current implementation follows the explanation of Colin de la Higuera's description of basic RPNI algorithm.

**Comment by emuskardin** [comment]
Only "heuristic" that is currently used is that you cannot merge 2 states that have different output value. This is far from an advance heuristic. This is just a simple optimization that will avoid merging states that have different output, as doing so would result in a automaton that would not conform with the data set

**Comment by wqqqy** [comment]
> Only "heuristic" that is currently used is that you cannot merge 2 states that have different output value. This is far from an advance heuristic. This is just a simple optimization that will avoid merging states that have different output, as doing so would result in a automaton that would not conform with the data set

Okay, thanks for the reply!
