### ISSUE TITLE
Issue with Examples.py

### ISSUE THREAD

**Issue by Rapfff** [DES-Lab/AALpy#36]
### Problem:
In _Examples.py_, line 189, I got `TypeError: cannot unpack non-iterable Mdp object` while doing:
`
mdp, input_alphabet = generate_random_mdp(num_states, input_len, num_outputs)
`

### Solution:
In _aalpy/utils/AutomatonGenerators.py_, line 269, replace:
`return Mdp(states[0], states)` by `return Mdp(states[0], states), inputs`

:)

**Comment by emuskardin** [comment]
Thanks, fixed :)

**Comment by emuskardin** [comment]
I will update the random MDP and SMM generation once I am back to work in a week or so. 
There are some other examples that deal with learning of stochastic models in Examples.py, which might be more suited for your needs. 

Btw, cool library with Baum-Welch algorithm, I was just thinking recently about adding those to AALpy :)
If you have some questions regarding anything let us know :)
