### ISSUE TITLE
Compute characterization set returns empty set if automata is not minimal

### ISSUE THREAD

**Issue by icezyclon** [DES-Lab/AALpy#38]
The function `compute_characterization_set` on `DeterministicAutomaton` returns an empty list (set) if the provided automata is not minimal. This might lead to confusion, as an empty characterization set might actually exists, e.g., automata with 1 state, which cannot directly be differentiated from a "not minimal" automaton.

I would recommend returning `None` in the case that the automata is not minimal (or raising an Exception) instead of returning the empty set.

**Comment by emuskardin** [comment]
Do I knooooooooooooooooooooow you? :p
Fixed :)

**Comment by emuskardin** [comment]
Knowing you, you will now request that == comparison between deterministic automata is enabled :p

**Comment by icezyclon** [comment]
> Do I knooooooooooooooooooooow you? :p Fixed :)

Did you also "fix" it in the tests? :P

> Knowing you, you will now request that == comparison between deterministic automata is enabled :p
> 
> Let me try doing that :p

Sure ;)

**Comment by icezyclon** [comment]
> Test passed, I even checked as I could not live with embarrassment if this change (that you requested) did not pass on existing tests :)
> 
> And as you surely know, test cases that do not exist are also passing test cases.

You are right. As we know `all(set()) == True` :1st_place_medal:  ;)
