### ISSUE TITLE
Invalid dot output because labels are malformed

### ISSUE THREAD

**Issue by pierreganty** [DES-Lab/AALpy#43]
With the following input alphabet 

```python
input_al = ['i', 'w', '<C-c>', '<C-g>', '<C-v>', 'c', ':', 'v', 'gh', '<C-o>', 'gr', '<Esc>', '<CR>']
```

the produced automaton (Moore machine) contains the following transitions:

```
s6 -> s2  [label=<C-v>];
s6 -> s1  [label=c];
s6 -> s1  [label=":"];
s6 -> s1  [label=v];
s6 -> s1  [label=gh];
s6 -> s21  [label=<C-o>];
```
The dot file is not accepted by the `dot` tool which complains about the presence of `<` in labels.
Also observe that the colon (`:`) is enclosed between quotes for some reason but not the other alphabet symbols.
Putting all the labels between quotes (e.g. `"<C-v>"`) fixes the issue.

**Comment by emuskardin** [comment]
Hi,

this seems to an issue with `pydot`, the library which we use for parsing and saving to .dot files.
As you said, one fix could be enforcing double quotes when writing the labels.

I will take a look and try to patch it.

**Comment by emuskardin** [comment]
Can you upgrade the AALpy with this command, test it out, and let me know if the problem persists.
```
pip install  --upgrade https://github.com/DES-Lab/AALpy/archive/master.zip
```

I tested it to some extend, I hope I did not introduce any new problems in the meantime, but it should not be the case (I hope) :)

**Comment by pierreganty** [comment]
Works for me. Thank you. I let you close the issue.

**Comment by emuskardin** [comment]
Thank you for pointing it out :)

One side tip: if you are doing active learning, you might consider using our implementation of KV (run_KV). With caching, it is much more query efficient than L*.
