### ISSUE TITLE
Out-of-memory (OOM) killer when using WMethod

### ISSUE THREAD

**Issue by 4ndynator** [DES-Lab/AALpy#47]
I am currently working on benchmarking combinations of learning algorithms and equivalence strategies for finding the optimal parameters.
When working with the WMethod, almost in every case when the maximum number of states is bigger than 10 and more than 6 items are in my learning alphabet, the learning script is killed by the OOM killer. 
My machine operates with 32gb of RAM which should be able to handle the learning.

I looked at the WMethod implementation and have some questions.
In the `find_cex()` method the test set is generated.
What is the point of shuffling and/or sorting the test set?

```
middle = []
for i in range(self.m + 1 - len(hypothesis.states)):
    middle.extend(list(product(self.alphabet, repeat=i)))

test_set = []
for seq in product(transition_cover, middle, hypothesis.characterization_set):
    inp_seq = tuple([i for sub in seq for i in sub])
    if inp_seq not in self.cache:
        test_set.append(inp_seq)

if self.shuffle:
    shuffle(test_set)
else:
    test_set.sort(key=len, reverse=True)
```

The problem with the memory usage lies in the fact that all test cases are generated and stored in a list first. With the WMethod, the number of test cases is huge.
I think this could be optimized by directly processing the generated test case, meaning there will be no large list that takes a lot of memory. This would mean that the test cases can not be sorted or shuffled though.

What do you think?

**Comment by emuskardin** [comment]
Thank you for pointing it out, and for providing a solution!
I have merged your commit. 

Ps.
Shuffle serves no practical purpose, as anyway all tests have to be executed. I do not remember why I have added it.
