### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by steve-anunknown** [DES-Lab/AALpy#67]
[This page](https://github.com/DES-Lab/AALpy/wiki/Learning-Deterministic-Systems) contains two broken links , specifically:

* https://des-lab.github.io/AALpy/documentation/aalpy/learning_algs/deterministic/LStar.html
* https://des-lab.github.io/AALpy/documentation/aalpy/learning_algs/deterministic/CounterExampleProcessing.html

I think that either the pages exist and the links should be fixed or they should just be removed.

**Comment by emuskardin** [comment]
Thank you. I also removed other broken links... I need to update/extend the wiki at some point :)
